### ISSUE TITLE
Unused imports

### ISSUE THREAD

**Issue by athlan** [aludwiko/fluentbuilder#21]
In some cases builder generates unused imports which does not comply CheckStyle policy:

```
import info.ludwikowski.fluentbuilder.common.AbstractBuilder;
import java.util.ArrayList;
import java.util.Arrays; <-- unused
import java.util.Date;
import java.util.List; <-- unused
```

Unused imports appears when one of attribute is `ArrayList<T>`

**Comment by aludwiko** [comment]
Do you mean e.g.:
```
public class ClassWithGenericTypes {
    private ArrayList<SimpleType> someList;
}
```? 
Is there a reason to use ArrayList instead of List?

**Comment by athlan** [comment]
I think that in most cases there is no reason to use `ArrayList` in code, but I met some case where (I think) it is important what data structure is used and checkstyle warning was generated.

After some considerations I think that this issue could be ignored ; )
